// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type User struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Phone     string       `json:"phone"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"createdAt"`
	UpdateAt  sql.NullTime `json:"updateAt"`
}
