// Code generated by sqlc. DO NOT EDIT.

package models

import (
	"fmt"
	"time"
)

type CompanyDeployModel string

const (
	CompanyDeployModelSaas    CompanyDeployModel = "saas"
	CompanyDeployModelPrivate CompanyDeployModel = "private"
)

func (e *CompanyDeployModel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompanyDeployModel(s)
	case string:
		*e = CompanyDeployModel(s)
	default:
		return fmt.Errorf("unsupported scan type for CompanyDeployModel: %T", src)
	}
	return nil
}

type CompanyModel string

const (
	CompanyModelFree   CompanyModel = "free"
	CompanyModelNormal CompanyModel = "normal"
	CompanyModelProd   CompanyModel = "prod"
)

func (e *CompanyModel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompanyModel(s)
	case string:
		*e = CompanyModel(s)
	default:
		return fmt.Errorf("unsupported scan type for CompanyModel: %T", src)
	}
	return nil
}

type Ok string

const (
	OkN Ok = "n"
	OkY Ok = "y"
)

func (e *Ok) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Ok(s)
	case string:
		*e = Ok(s)
	default:
		return fmt.Errorf("unsupported scan type for Ok: %T", src)
	}
	return nil
}

type Account struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Phone     string    `json:"phone"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"createdAt"`
	UpdateAt  time.Time `json:"updateAt"`
}

type Actor struct {
	ID          int32     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
}

type ActorPermission struct {
	ID           int32  `json:"id"`
	ActorID      int32  `json:"actorID"`
	Name         string `json:"name"`
	CompanyRead  Ok     `json:"companyRead"`
	EmployCreate Ok     `json:"employCreate"`
	EmployRead   Ok     `json:"employRead"`
	EmployUpdate Ok     `json:"employUpdate"`
	EmployDelete Ok     `json:"employDelete"`
}

type Company struct {
	ID          int32              `json:"id"`
	AccountID   int32              `json:"accountID"`
	Name        string             `json:"name"`
	People      string             `json:"people"`
	Model       CompanyModel       `json:"model"`
	DeployModel CompanyDeployModel `json:"deployModel"`
	CreatedAt   time.Time          `json:"createdAt"`
	UpdateAt    time.Time          `json:"updateAt"`
}

type Employ struct {
	ID        int32     `json:"id"`
	AccountID int32     `json:"accountID"`
	CompanyID int32     `json:"companyID"`
	CreatedAt time.Time `json:"createdAt"`
	UpdateAt  time.Time `json:"updateAt"`
}

type EmployActor struct {
	ID        int32     `json:"id"`
	EmployID  int32     `json:"employID"`
	ActorID   int32     `json:"actorID"`
	CreatedAt time.Time `json:"createdAt"`
}
