// Code generated by sqlc. DO NOT EDIT.

package models

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Phone     string         `json:"phone"`
	Email     sql.NullString `json:"email"`
	Password  string         `json:"password"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdateAt  time.Time      `json:"updateAt"`
}

type Author struct {
	ID           int32          `json:"id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	CreatedAt    time.Time      `json:"createdAt"`
	CompanyRead  bool           `json:"companyRead"`
	EmployCreate bool           `json:"employCreate"`
	EmployRead   bool           `json:"employRead"`
	EmployUpdate bool           `json:"employUpdate"`
	EmployDelete bool           `json:"employDelete"`
}

type Company struct {
	ID          int32     `json:"id"`
	Name        string    `json:"name"`
	People      int32     `json:"people"`
	Model       int16     `json:"model"`
	DeployModel int16     `json:"deployModel"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdateAt    time.Time `json:"updateAt"`
}

type Employ struct {
	ID        int32     `json:"id"`
	AccountID int32     `json:"accountID"`
	CompanyID int32     `json:"companyID"`
	Boss      bool      `json:"boss"`
	CreatedAt time.Time `json:"createdAt"`
	UpdateAt  time.Time `json:"updateAt"`
}

type EmployAuthor struct {
	ID        int32     `json:"id"`
	EmployID  int32     `json:"employID"`
	AuthorID  int32     `json:"authorID"`
	CreatedAt time.Time `json:"createdAt"`
}
